services:
  db:
    container_name: postgres-pertitrack
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: pertitrack
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db: