name: Java CI with Maven

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file backend/pom.xml
        env:
          DB_URI: jdbc:h2:mem:testdb
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_DRIVER_NAME: org.h2.Driver
          DDL_HANDLING: update
          JPA_DATABASE: h2
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          JWT_EXPIRATION_MS: 86400000